### PR TITLE
Added Scalingo deployment documentation

### PR DESCRIPTION
**Pull request by brandon-welsch**
Added documentation for Scalingo one-click deployment

### CODE REVIEW

**Comment by Yukaii** [comment]
@brandon-welsch I see you provide custom branch deployment description in PR https://github.com/hackmdio/codimd/pull/1360, would you like to add them to docs? 🤩

**Comment by Yukaii** [comment]
And another question for this, which branch will be used for scarlingo deployment? Is the master branch or the default branch set in GitHub repository? 

Take our heroku deployment as an example, it's specified to use `master` branch because we do releases on master branch, but use `develop` branch as default branch on GitHub.

**Comment by brandon-welsch** [comment]
> @brandon-welsch I see you provide custom branch deployment description in PR [hackmdio/codimd#1360](https://github.com/hackmdio/codimd/pull/1360), would you like to add them to docs? 🤩

Good point, I will add it thanks.

> And another question for this, which branch will be used for scarlingo deployment? Is the master branch or the default branch set in GitHub repository?
> 
> Take our heroku deployment as an example, it's specified to use `master` branch because we do releases on master branch, but use `develop` branch as default branch on GitHub.

Scalingo deployment uses the `master` branch in all cases ;)

**Comment by Yukaii** [comment]
Looks good to me now 😍 

Just a reminder that we won't put this online until we do our next release :)

Thanks for your contribution @brandon-welsch !

**Comment by brandon-welsch** [comment]
Thanks to you especially, CodiMD is a tool that I personally love

**Pull request merged**
